AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  searchphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      # FunctionName: searchphotos2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./searchphotos
      Description: "Lambda function for CD and searchphotos"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::021253950508:role/service-role/searchphotos-role-kkm00am3"
      Environment:
        Variables:
          REGION: us-east-1
  indexphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      # FunctionName: indexphotos2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./indexphotos
      Description: "Lambda function for CD and indexphotos"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::021253950508:role/service-role/indexphotos-role-a4ogic51"
      Environment:
        Variables:
          REGION: us-east-1